import type {
  Category,
  DailyCompletion,
  Habit,
  Profile,
  Quest,
  Supplement,
  XpEvent,
} from "@/types/database";
import { todayISO } from "./utils";

const GUEST_ID = "guest-demo-user";

export const DEMO_PROFILE: Profile = {
  id: GUEST_ID,
  display_name: "Hunter",
  avatar_url: null,
  player_level: 12,
  total_xp: 4850,
  power_score: 72,
  discipline_score: 68,
  momentum_score: 81,
  consistency_score: 74,
  rank: "C",
  is_guest: true,
  settings: {},
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const DEMO_CATEGORIES: Category[] = [
  {
    id: "cat-physical",
    user_id: null,
    parent_id: null,
    slug: "physical",
    name: "Physical",
    description: "Body mastery",
    icon: "dumbbell",
    color: "#00d4ff",
    category_type: "core",
    sort_order: 1,
    base_xp: 15,
    level: 8,
    total_xp: 1240,
    current_streak: 5,
    longest_streak: 21,
    rank: "C",
    is_system: true,
    metadata: {},
    created_at: "",
    updated_at: "",
  },
  {
    id: "cat-mental",
    user_id: null,
    parent_id: null,
    slug: "mental",
    name: "Mental",
    description: "Mind expansion",
    icon: "brain",
    color: "#a855f7",
    category_type: "core",
    sort_order: 2,
    base_xp: 15,
    level: 7,
    total_xp: 980,
    current_streak: 12,
    longest_streak: 30,
    rank: "C",
    is_system: true,
    metadata: {},
    created_at: "",
    updated_at: "",
  },
  {
    id: "cat-awareness",
    user_id: null,
    parent_id: null,
    slug: "awareness",
    name: "Awareness",
    description: "Self knowledge",
    icon: "eye",
    color: "#22d3ee",
    category_type: "core",
    sort_order: 3,
    base_xp: 15,
    level: 5,
    total_xp: 620,
    current_streak: 3,
    longest_streak: 14,
    rank: "D",
    is_system: true,
    metadata: {},
    created_at: "",
    updated_at: "",
  },
  {
    id: "cat-vitality",
    user_id: null,
    parent_id: null,
    slug: "vitality",
    name: "Vitality",
    description: "Life force",
    icon: "heart-pulse",
    color: "#10b981",
    category_type: "core",
    sort_order: 4,
    base_xp: 15,
    level: 9,
    total_xp: 1580,
    current_streak: 8,
    longest_streak: 45,
    rank: "B",
    is_system: true,
    metadata: {},
    created_at: "",
    updated_at: "",
  },
];

function habit(
  slug: string,
  name: string,
  categorySlug: string,
  icon: string,
  baseXp: number,
  streak: number,
  completed = false,
  targetValue?: number,
  unit?: string,
  currentValue?: number,
  preferredPeriod?: string
): Habit {
  return {
    id: `habit-${slug}`,
    user_id: null,
    category_id: `cat-${categorySlug}`,
    skill_id: null,
    slug,
    name,
    description: null,
    icon,
    base_xp: baseXp,
    level: Math.max(1, Math.floor(streak / 3)),
    total_xp: baseXp * streak * 5,
    current_streak: streak,
    longest_streak: streak + 5,
    target_value: targetValue ?? null,
    unit: unit ?? null,
    is_system: true,
    is_active: true,
    metadata: {
      category_slug: categorySlug,
      ...(currentValue != null ? { current_value: currentValue } : {}),
      ...(preferredPeriod ? { preferred_period: preferredPeriod } : {}),
    },
    created_at: "",
    updated_at: "",
    completed_today: completed,
  };
}

export const DEMO_HABITS: Habit[] = [
  habit("steps_5k", "Steps 5k", "physical", "footprints", 15, 5, false, 5000, "steps", 3200),
  habit("workout_habit", "Workout", "physical", "dumbbell", 25, 5, false),
  habit("flexibility", "Flexibility", "physical", "stretch", 15, 2, true),
  habit("sports_habit", "Sports", "physical", "trophy", 20, 0, false),
  habit("fighting_habit", "Fighting", "physical", "swords", 25, 1, false),
  habit("mobility", "Mobility", "physical", "move", 15, 4, true),
  habit("meditate", "Meditate", "mental", "flower-2", 15, 12, true),
  habit("puzzles", "Puzzles", "mental", "puzzle", 10, 3, false),
  habit("work", "Work", "mental", "briefcase", 20, 8, true),
  habit("read", "Read", "mental", "book-open", 15, 6, false),
  habit("upskill", "Upskill", "mental", "graduation-cap", 20, 4, true),
  habit("poker", "Poker", "mental", "spade", 10, 0, false),
  habit("news", "News", "mental", "newspaper", 10, 7, true),
  habit("journal", "Journal", "awareness", "notebook-pen", 15, 3, true),
  habit("diet_tracking", "Diet Tracking", "awareness", "apple", 15, 5, false),
  habit("weight_tracking", "Weight Tracking", "awareness", "scale", 10, 2, true),
  habit("follow_diet", "Follow Diet", "vitality", "salad", 20, 8, true),
  habit("water_intake", "Water Intake", "vitality", "droplets", 10, 15, false, 8, "glasses", 5),
  habit("dont_smoke", "Don't Smoke", "vitality", "ban", 25, 30, true),
  habit("sleep", "Sleep", "vitality", "moon", 20, 7, false, 7, "hours", 6),
  habit("skincare", "Skincare", "vitality", "sparkles", 10, 5, false),
  habit("haircare", "Haircare", "vitality", "scissors", 10, 4, true),
  habit("beardcare", "Beardcare", "vitality", "user", 10, 3, false),
];

export const DEMO_SUPPLEMENTS: Supplement[] = [
  {
    id: "sup-protein",
    user_id: null,
    slug: "protein",
    name: "Protein",
    description: null,
    base_xp: 5,
    level: 6,
    total_xp: 420,
    current_streak: 14,
    longest_streak: 30,
    adherence_score: 92,
    is_system: true,
    is_active: true,
    created_at: "",
    updated_at: "",
    taken_today: true,
  },
  {
    id: "sup-creatine",
    user_id: null,
    slug: "creatine",
    name: "Creatine",
    description: null,
    base_xp: 5,
    level: 5,
    total_xp: 310,
    current_streak: 10,
    longest_streak: 25,
    adherence_score: 85,
    is_system: true,
    is_active: true,
    created_at: "",
    updated_at: "",
    taken_today: true,
  },
  {
    id: "sup-fish_oil",
    user_id: null,
    slug: "fish_oil",
    name: "Fish Oil",
    description: null,
    base_xp: 5,
    level: 4,
    total_xp: 180,
    current_streak: 7,
    longest_streak: 14,
    adherence_score: 78,
    is_system: true,
    is_active: true,
    created_at: "",
    updated_at: "",
    taken_today: false,
  },
  {
    id: "sup-magnesium",
    user_id: null,
    slug: "magnesium",
    name: "Magnesium Glycinate",
    description: null,
    base_xp: 5,
    level: 3,
    total_xp: 95,
    current_streak: 5,
    longest_streak: 12,
    adherence_score: 70,
    is_system: true,
    is_active: true,
    created_at: "",
    updated_at: "",
    taken_today: true,
  },
  {
    id: "sup-vitamin_d3",
    user_id: null,
    slug: "vitamin_d3",
    name: "Vitamin D3 + Calcium",
    description: null,
    base_xp: 5,
    level: 4,
    total_xp: 150,
    current_streak: 8,
    longest_streak: 20,
    adherence_score: 82,
    is_system: true,
    is_active: true,
    created_at: "",
    updated_at: "",
    taken_today: true,
  },
];

export const DEMO_QUESTS: Quest[] = [
  {
    id: "q-daily-physical",
    user_id: null,
    slug: "complete_physical",
    title: "Physical Dominion",
    description: "Complete all physical habits today",
    quest_type: "daily",
    status: "active",
    target_count: 6,
    current_count: 3,
    xp_reward: 75,
    rank_required: null,
    category_id: "cat-physical",
    is_system: true,
    expires_at: null,
    completed_at: null,
    metadata: { category_slug: "physical" },
    created_at: "",
    updated_at: "",
  },
  {
    id: "q-perfect-day",
    user_id: null,
    slug: "perfect_day",
    title: "Perfect Day",
    description: "Complete every habit across all categories",
    quest_type: "daily",
    status: "active",
    target_count: 22,
    current_count: 14,
    xp_reward: 200,
    rank_required: null,
    category_id: null,
    is_system: true,
    expires_at: null,
    completed_at: null,
    metadata: {},
    created_at: "",
    updated_at: "",
  },
  {
    id: "q-sleep-streak",
    user_id: null,
    slug: "sleep_streak_7",
    title: "Sleep Guardian",
    description: "Maintain a 7-day sleep streak",
    quest_type: "weekly",
    status: "active",
    target_count: 7,
    current_count: 7,
    xp_reward: 150,
    rank_required: null,
    category_id: null,
    is_system: true,
    expires_at: null,
    completed_at: null,
    metadata: { habit_slug: "sleep" },
    created_at: "",
    updated_at: "",
  },
  {
    id: "q-no-smoke",
    user_id: null,
    slug: "no_smoke_30",
    title: "Smoke Free Monarch",
    description: "30 days without smoking",
    quest_type: "main",
    status: "active",
    target_count: 30,
    current_count: 30,
    xp_reward: 500,
    rank_required: "B",
    category_id: null,
    is_system: true,
    expires_at: null,
    completed_at: null,
    metadata: { habit_slug: "dont_smoke" },
    created_at: "",
    updated_at: "",
  },
  {
    id: "q-deep-work",
    user_id: null,
    slug: "deep_work_marathon",
    title: "Deep Work Dungeon",
    description: "4 hours of focused work in one session",
    quest_type: "dungeon",
    status: "active",
    target_count: 8,
    metadata: { categories: ["physical", "mental", "awareness", "vitality"] },
    current_count: 0,
    xp_reward: 300,
    rank_required: null,
    category_id: null,
    is_system: true,
    expires_at: null,
    completed_at: null,
    created_at: "",
    updated_at: "",
  },
];

export const DEMO_DAILY: DailyCompletion = {
  id: "daily-1",
  user_id: GUEST_ID,
  completion_date: todayISO(),
  physical_complete: false,
  mental_complete: false,
  awareness_complete: false,
  vitality_complete: false,
  perfect_day: false,
  total_habits: 22,
  completed_habits: 14,
  total_xp: 285,
  metadata: {},
  created_at: new Date().toISOString(),
};

export const DEMO_XP_EVENTS: XpEvent[] = [
  {
    id: "xp-1",
    user_id: GUEST_ID,
    entity_type: "habit",
    entity_id: "habit-meditate",
    base_xp: 15,
    final_xp: 42,
    streak_multiplier: 1.75,
    combo_multiplier: 1.25,
    consistency_multiplier: 1.2,
    momentum_multiplier: 1.15,
    bonus_multiplier: 1,
    reason: "Meditate completed",
    metadata: {},
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "xp-2",
    user_id: GUEST_ID,
    entity_type: "habit",
    entity_id: "habit-sleep",
    base_xp: 20,
    final_xp: 56,
    streak_multiplier: 1.75,
    combo_multiplier: 1.5,
    consistency_multiplier: 1.35,
    momentum_multiplier: 1.25,
    bonus_multiplier: 1,
    reason: "Sleep logged",
    metadata: {},
    created_at: new Date(Date.now() - 7200000).toISOString(),
  },
];

import {
  buildSeedSkills,
  buildSeedSports,
  buildSeedExercises,
} from "@/lib/seed-workout-system";
import { rollupSkillTree } from "@/lib/workout-progression";

export function getDemoDashboard() {
  const remap = (id: string) => id;
  const skills = buildSeedSkills(remap);
  const sports = buildSeedSports(remap);
  const exercises = buildSeedExercises(remap, skills);
  rollupSkillTree(skills);

  return {
    profile: DEMO_PROFILE,
    categories: DEMO_CATEGORIES,
    habits: DEMO_HABITS,
    supplements: DEMO_SUPPLEMENTS,
    quests: DEMO_QUESTS,
    dailyCompletion: DEMO_DAILY,
    recentXpEvents: DEMO_XP_EVENTS,
    skills,
    sports,
    exercises,
    workoutSessions: [],
    workoutLogs: [],
    todayXpEarned: DEMO_DAILY.total_xp,
  };
}
