import type { DashboardStats } from "@/types/database";
import { getExtended } from "@/lib/player-settings-extended";
import { getPlayerSettings } from "@/lib/player-settings";

export function generateWeeklyReportMarkdown(state: DashboardStats): string {
  const now = new Date();
  const weekXp = state.recentXpEvents
    .filter((e) => now.getTime() - new Date(e.created_at).getTime() < 7 * 86400000)
    .reduce((s, e) => s + e.final_xp, 0);

  const topStreaks = [...state.habits]
    .filter((h) => h.is_active)
    .sort((a, b) => b.current_streak - a.current_streak)
    .slice(0, 5);

  const categories = state.categories
    .map((c) => `- **${c.name}**: Lv.${c.level}, ${c.total_xp} XP`)
    .join("\n");

  const perfectDays =
    (state.dailyCompletion?.metadata?.perfect_days_week as string[]) ?? [];
  const focus = getPlayerSettings(state.profile).weekly_focus ?? "Not set";
  const coins = getExtended(state.profile).shadow_coins ?? 0;

  return `# Forge Weekly Report
**Week of ${now.toISOString().slice(0, 10)}**

## Summary
- Player: Lv.${state.profile.player_level} (${state.profile.rank})
- XP this week: **${weekXp}**
- Perfect days: **${perfectDays.length}**
- Shadow coins: **${coins}**
- Weekly focus: ${focus}

## Categories
${categories}

## Top Streaks
${topStreaks.map((h) => `- ${h.name}: ${h.current_streak}d`).join("\n") || "- None"}

## Quests
${state.quests
  .filter((q) => q.status === "active")
  .slice(0, 5)
  .map((q) => `- [${q.quest_type}] ${q.title} (${q.current_count}/${q.target_count})`)
  .join("\n") || "- No active quests"}

---
*Generated by JARVIS*
`;
}
