import type { DashboardStats } from "@/types/database";
import { categoryBalance, habitROIRanking, sleepPerfectDayCorrelation } from "@/lib/analytics-correlation";
import { computeBodyCompScore } from "@/lib/body-comp-score";
import { getExtended } from "@/lib/player-settings-extended";

export function buildMonthlyReport(state: DashboardStats): string {
  const now = new Date();
  const month = now.toLocaleString("default", { month: "long", year: "numeric" });
  const balance = categoryBalance(state);
  const roi = habitROIRanking(state).slice(0, 5);
  const sleep = sleepPerfectDayCorrelation(state);
  const measurements = getExtended(state.profile).body_measurements ?? [];
  const bodyComp = computeBodyCompScore(measurements);

  const lines = [
    `# Evolution Report — ${month}`,
    "",
    `**Hunter:** ${state.profile.display_name ?? "Hunter"} · Rank ${state.profile.rank} · Level ${state.profile.player_level}`,
    "",
    "## Category Balance",
    ...Object.entries(balance).map(([k, v]) => `- ${k}: ${v}%`),
    "",
    "## Top Habit ROI (perfect-day correlation)",
    ...roi.map((r) => `- ${r.title}: ${r.score}%`),
    "",
    "## Sleep ↔ Perfect Days",
    sleep.dataPoints.length > 0
      ? `Avg sleep delta on perfect days: ${sleep.correlation >= 0 ? "+" : ""}${sleep.correlation}h`
      : "Not enough health data yet — sync Apple Health or import manually.",
    "",
    "## Body Composition",
    bodyComp.score > 0 ? `Score: ${bodyComp.score}/100 — ${bodyComp.trend}` : "Log measurements in Stats to track.",
    "",
    "## Streaks",
    `- Longest active streak: ${Math.max(0, ...state.habits.filter((h) => h.is_active).map((h) => h.current_streak))} days`,
    `- Shadow coins: ${getExtended(state.profile).shadow_coins ?? 0}`,
    "",
    "_Generated by JARVIS · Keep evolving._",
  ];

  return lines.join("\n");
}

export function buildDossierReport(state: DashboardStats): string {
  const monthly = buildMonthlyReport(state);
  const questsDone = state.quests.filter((q) => q.status === "completed").length;
  const achievements = Object.keys(getExtended(state.profile).achievements_unlocked ?? {}).length;

  return [
    monthly,
    "",
    "---",
    "",
    "## Full Dossier",
    `- Quests completed: ${questsDone}`,
    `- Achievements unlocked: ${achievements}`,
    `- Total XP: ${state.profile.total_xp}`,
    `- Active habits: ${state.habits.filter((h) => h.is_active).length}`,
  ].join("\n");
}
