[theme]
base = "dark"
primaryColor = "#ededed"
backgroundColor = "#050505"
secondaryBackgroundColor = "#0c0c0c"
textColor = "#ededed"
font = "sans serif"

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[server]
headless = true

[client]
toolbarMode = "minimal"
